INSERT INTO nationality (nationality_name, nationality_code) VALUES
('Indonesia', 'ID'),
('Malaysia', 'MY'),
('Singapore', 'SG'),
('Thailand', 'TH'),
('Philippines', 'PH'),
('Vietnam', 'VN'),
('Brunei', 'BN'),
('Cambodia', 'KH'),
('Laos', 'LA'),
('Myanmar', 'MM'),
('Japan', 'JP'),
('South Korea', 'KR'),
('China', 'CN'),
('Taiwan', 'TW'),
('Hong Kong', 'HK'),
('India', 'IN'),
('Pakistan', 'PK'),
('Bangladesh', 'BD'),
('Sri Lanka', 'LK'),
('Nepal', 'NP'),
('United States', 'US'),
('Canada', 'CA'),
('Mexico', 'MX'),
('Brazil', 'BR'),
('Argentina', 'AR'),
('United Kingdom', 'GB'),
('France', 'FR'),
('Germany', 'DE'),
('Italy', 'IT'),
('Spain', 'ES'),
('Netherlands', 'NL'),
('Portugal', 'PT'),
('Switzerland', 'CH'),
('Sweden', 'SE'),
('Norway', 'NO'),
('Denmark', 'DK'),
('Finland', 'FI'),
('Poland', 'PL'),
('Russia', 'RU'),
('Turkey', 'TR'),
('Saudi Arabia', 'SA'),
('United Arab Emirates', 'AE'),
('Qatar', 'QA'),
('Egypt', 'EG'),
('South Africa', 'ZA'),
('Nigeria', 'NG'),
('Kenya', 'KE'),
('Australia', 'AU'),
('New Zealand', 'NZ')
ON CONFLICT (nationality_code) DO NOTHING;